environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BUILD_TYPE: "MSVC_2017"
    - BUILD_TYPE: "MSVC_64_Debug"

install:
- if [%BUILD_TYPE%]==[MSVC_64_Debug] set PATH=C:\Miniconda37-x64\Scripts;%PATH%
- if [%BUILD_TYPE%]==[MSVC_64_Debug] conda config --add channels conda-forge --force
- if [%BUILD_TYPE%]==[MSVC_64_Debug] conda update --all -y
- if [%BUILD_TYPE%]==[MSVC_64_Debug] conda create -y --name pagmo python=3.7 cmake boost-cpp eigen nlopt tbb tbb-devel
- if [%BUILD_TYPE%]==[MSVC_64_Debug] call activate pagmo

- if [%BUILD_TYPE%]==[MSVC_2017] set PATH=C:\Miniconda37-x64\Scripts;%PATH%
- if [%BUILD_TYPE%]==[MSVC_2017] conda config --add channels conda-forge --force
- if [%BUILD_TYPE%]==[MSVC_2017] conda update --all -y
- if [%BUILD_TYPE%]==[MSVC_2017] conda create -y --name pagmo python=3.7 cmake boost-cpp eigen nlopt tbb tbb-devel
- if [%BUILD_TYPE%]==[MSVC_2017] call activate pagmo

build_script:
- if [%BUILD_TYPE%]==[MSVC_64_Debug] mkdir build
- if [%BUILD_TYPE%]==[MSVC_64_Debug] cd build
- if [%BUILD_TYPE%]==[MSVC_64_Debug] cmake -G "Visual Studio 14 2015 Win64" -DBoost_NO_BOOST_CMAKE=ON -DCMAKE_INSTALL_PREFIX=%CONDA_PREFIX%/Library -DPAGMO_BUILD_TESTS=YES -DPAGMO_BUILD_TUTORIALS=YES -DPAGMO_WITH_EIGEN3=yes -DPAGMO_WITH_NLOPT=yes ..
- if [%BUILD_TYPE%]==[MSVC_64_Debug] cmake --build . --config Release --target install

- if [%BUILD_TYPE%]==[MSVC_2017] mkdir build
- if [%BUILD_TYPE%]==[MSVC_2017] cd build
- if [%BUILD_TYPE%]==[MSVC_2017] cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_CXX_STANDARD=17 -DBoost_NO_BOOST_CMAKE=ON -DCMAKE_INSTALL_PREFIX=%CONDA_PREFIX%/Library -DPAGMO_BUILD_TESTS=YES -DPAGMO_BUILD_TUTORIALS=YES -DPAGMO_WITH_EIGEN3=yes -DPAGMO_WITH_NLOPT=yes ..
- if [%BUILD_TYPE%]==[MSVC_2017] cmake --build . --config Release --target install

test_script:
- if [%BUILD_TYPE%]==[MSVC_64_Debug] ctest -VV --output-on-failure

- if [%BUILD_TYPE%]==[MSVC_2017] ctest -VV --output-on-failure


notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/1a3742192bd3f7e6d8e2

# Enable this to be able to login to the build worker. You can use the
# `remmina` program in Ubuntu, use the login information that the line below
# prints into the log.
# on_finish:
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
