version: 2

jobs:
  bionic_gcc7_coverage:
    docker:
    - image: circleci/buildpack-deps:bionic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_bionic_gcc7_coverage.sh
  cosmic_gcc8:
    docker:
    - image: circleci/buildpack-deps:cosmic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_cosmic_gcc8.sh
  cosmic_clang7:
    docker:
    - image: circleci/buildpack-deps:cosmic
    steps:
    - checkout
    - run:
        name: Build and test
        command: bash ./tools/circleci_cosmic_clang7.sh

workflows:
  version: 2
  all_builds:
    jobs:
    - bionic_gcc7_coverage
    - cosmic_gcc8
    - cosmic_clang7
